services:
  frontend:
    image: node:20-alpine
    container_name: kyskfilms-frontend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_KEYCLOAK_URL=http://kyskfilms-keycloak:8081
      - REACT_APP_BACKEND_URL=http://kyskfilms-backend:8082
    command: sh -c "npm install --legacy-peer-deps && npm start"
    networks:
      - backend_kyskfilms-network

networks:
  backend_kyskfilms-network:
    external: true
